//! `adapter-chunker-recursive` — a faithful Rust port of LangChain's
//! `RecursiveCharacterTextSplitter` plus a markdown-header breadcrumb pass (issue 027).
//!
//! The splitter modules are validated byte-for-byte against the Python gold standard in
//! `fixtures/golden_vectors.json` (generated by `experiments/chunking/gen_golden.py`).
//! The experiment series in `experiments/chunking/RESULTS.md` selected this chunker
//! (recursive + breadcrumbs, ~512-token target) over the blank-line chunker.

pub mod markdown;
pub mod recursive;

use librarian_domain::{
    AdapterIdentity, BookMeta, Chunk, ChunkId, ChunkPayload, Chunker, CodeMeta, ConfigHash,
    ContentType, Document, ExtractedText, PaperMeta, Provenance, StageVersion,
};

/// Field-standard defaults from the experiment series (~512 tokens ≈ 2000 chars, ~10% overlap).
const DEFAULT_MAX_CHARS: usize = 2000;
const DEFAULT_OVERLAP: usize = 200;

/// Recursive + markdown-breadcrumb chunker (issue 027). Joins the extracted spans into one
/// markdown document, applies the header → breadcrumb → recursive-pack pipeline, and emits
/// one `Chunk` per piece. Sizes are in characters (LangChain semantics).
pub struct RecursiveChunker {
    pub chunk_size: usize,
    pub chunk_overlap: usize,
}

impl Default for RecursiveChunker {
    fn default() -> Self {
        Self {
            chunk_size: DEFAULT_MAX_CHARS,
            chunk_overlap: DEFAULT_OVERLAP,
        }
    }
}

impl RecursiveChunker {
    pub fn new() -> Self {
        Self::default()
    }

    /// Construct with an explicit budget. `chunk_size` must be non-zero.
    pub fn with_budget(chunk_size: usize, chunk_overlap: usize) -> Self {
        assert!(chunk_size > 0, "chunk_size must be non-zero");
        Self {
            chunk_size,
            chunk_overlap,
        }
    }
}

#[derive(Debug, thiserror::Error)]
#[error("recursive chunker: empty input")]
pub struct RecursiveChunkError;

impl AdapterIdentity for RecursiveChunker {
    fn name(&self) -> &str {
        "chunker-recursive"
    }
    fn version(&self) -> StageVersion {
        StageVersion("0.1.0".into())
    }
    fn config_hash(&self) -> ConfigHash {
        ConfigHash(format!(
            "chunk_size={};overlap={}",
            self.chunk_size, self.chunk_overlap
        ))
    }
}

impl Chunker for RecursiveChunker {
    type Error = RecursiveChunkError;

    fn chunk(&self, doc: &Document, text: ExtractedText) -> Result<Vec<Chunk>, Self::Error> {
        if text.spans.is_empty() {
            return Err(RecursiveChunkError);
        }
        let file = doc.path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        // Chunk each span independently so the originating page survives onto every chunk.
        // For single-span markdown (the text extractor's output) this is identical to
        // whole-document chunking; for multi-span sources (PDF pages) it preserves the page.
        let mut chunks = Vec::new();
        let mut index: u32 = 0;
        for span in &text.spans {
            let pieces =
                markdown::chunk_markdown(&span.text, file, self.chunk_size, self.chunk_overlap);
            for piece in pieces {
                chunks.push(make_chunk(doc, index, piece, span.page));
                index += 1;
            }
        }
        if chunks.is_empty() {
            return Err(RecursiveChunkError);
        }
        Ok(chunks)
    }
}

/// Build the typed `ChunkPayload` for `doc`'s content type. Title is the file stem; `page`
/// is the originating span's page (when the source tracks pages, e.g. PDFs).
fn payload_for(doc: &Document, title: &str, page: Option<u32>) -> ChunkPayload {
    match doc.content_type {
        ContentType::Book => ChunkPayload::Book(BookMeta {
            title: title.to_string(),
            author: None,
            chapter: None,
            section: None,
            page,
        }),
        ContentType::Paper => ChunkPayload::Paper(PaperMeta {
            title: title.to_string(),
            authors: vec![],
            section: None,
            page_start: page,
            page_end: page,
        }),
        ContentType::Code => ChunkPayload::Code(CodeMeta {
            repo: None,
            commit: None,
            file_path: doc.path.display().to_string(),
            language: None,
            symbol: None,
        }),
    }
}

/// Build one domain `Chunk` from a breadcrumb-prefixed `text` at position `index` in `doc`,
/// carrying the originating span's `page`.
fn make_chunk(doc: &Document, index: u32, text: String, page: Option<u32>) -> Chunk {
    let title = doc
        .path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_string();
    Chunk {
        chunk_id: ChunkId(format!("{}#{}", doc.source_id.0, index)),
        source_id: doc.source_id.clone(),
        chunk_index: index,
        payload: payload_for(doc, &title, page),
        text,
        provenance: Provenance::default(),
    }
}
